### ISSUE TITLE
Wait behaviour when no work to do

### ISSUE THREAD

**Issue by minijackson** [ctbur/async#4]
Hello, and thanks for the awesome project!

I've been playing around with it for a bit, a stumbled across an issue that I've reduced to:

```
async -s socket.S server --start
async -s socket.S wait
async -s socket.S wait
```

The last line errors out, and "kills" the server, complaining: `Can only wait once at a time`

Cheers!

**Comment by ctbur** [comment]
Thanks! :) Let me know when you find something else or if you have a suggestion.
